### ISSUE TITLE
Documentation unclear re: "mainTemplate"

### ISSUE THREAD

**Issue by SavedByZero** [Countly/countly-sdk-unity#157]
Can you please be more specific about how to add our application Id to mainTemplate besides linking us to a general unity manual section on Gradle?  That section explains nothing intelligible about how to do that, and not all of us multi platform devs speak Gradle.  Please just say exactly where in the file it goes and what the proper field name is, with an example.  Thanks!

Also: There's no iOS setup documentation outside of the push notifications section, and the link to the SDK further down in the readme is broken.

**Comment by ArtursKadikis** [comment]
Hello, I'm not sure what you mean with your questions and it doesn't really sound like you are referencing our SDK documentation that can be found here:
https://support.count.ly/hc/en-us/articles/360037813851-Unity

" how to add our application Id to mainTemplate" - what aplication ID and what "mainTemplate"?
" besides linking us to a general unity manual section on Gradle" - I'm not sure where that would be happening.
"and the link to the SDK further down in the readme is broken." - I'm not sure which link in which readme you are referencing

**Comment by SavedByZero** [comment]
My questions refer to your own readme file, right on this site. 

Glad to know that the SDK instructions in that link is more up to date as it seems to work much more easily (although there seems to be a documented step missing between the use of Countly with a capital 'C' and the lowercase version, but I will check the example code in unity to see what's missing).

**Comment by ArtursKadikis** [comment]
I think I understand what you mean. That was an outdated documentation that was located in the readme. We just replaced it. The older document can be found here:
https://github.com/Countly/countly-sdk-unity/tree/66907fe8eb248332f97ab2c3d02f0a93d82f6d74

The lover case "countly" is just a convenience local variable that your app could have that would store the reference of the global instance:
`Countly countly = Countly.Instance;`

Since this issue mentions problems about the outdated documentation, I will close this issue for now.
